@baseUrl = https://aoi.github.com
@token = 
@acceptHeader = application/vnd.github.v3.html+json

GET {{baseUrl}}/user/starred
    ?page=1
Authorization: bearer {{token}}
Accept: {{acceptHeader}}

### 

GET {{baseUrl}}/search/repositories
    ?q=flutter
    &page=1
Authorization: bearer {{token}}
Accept: {{acceptHeader}}

###

GET {{baseUrl}}/repos/flutter/flutter/readme
Authorization: bearer {{token}}
Accept: {{acceptHeader}}

###
PUT {{baseUrl}}/user/starred/ResoDev/foundations-stateful-widget
Authorization: bearer {{token}}
Content-Length: 0
Accept: {{acceptHeader}}

###
DELETE {{baseUrl}}/user/starred/ResoDev/foundations-stateful-widget
Authorization: bearer {{token}}
Accept: {{acceptHeader}}

###
GET {{baseUrl}}/user/starred/ResoDev/foundations-stateful-widget
Authorization: bearer {{token}}
Accept: {{acceptHeader}}
